// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config'
import { defineConfig } from 'prisma/config'

export default defineConfig({
	earlyAccess: true,
	schema: path.join('prisma', 'schema.prisma'),
	migrate: {
		async adapter() {
			const { PrismaNeon } = await import('@prisma/adapter-neon')
			return new PrismaNeon({ connectionString: process.env.DATABASE_URL })
		},
	},
})
