import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer'

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 11,
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 20,
  },
  title: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 11,
    color: '#666',
  },
  table: {
    marginTop: 16,
  },
  tableHeader: {
    flexDirection: 'row',
    borderBottomWidth: 2,
    borderBottomColor: '#333',
    paddingVertical: 8,
    fontWeight: 'bold',
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#e5e5e5',
    paddingVertical: 8,
  },
  colNumber: { width: '10%' },
  colName: { width: '50%' },
  colStudentNumber: { width: '40%' },
  footer: {
    marginTop: 24,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#e5e5e5',
  },
  footerText: {
    fontSize: 10,
    color: '#666',
  },
})

interface Props {
  className: string
  level: string | null
  students: { name: string; studentNumber: string }[]
}

export function ClassRosterPDF({ className, level, students }: Props) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>Class Roster</Text>
          <Text style={styles.subtitle}>
            {className} {level ? `— ${level}` : ''}
          </Text>
          <Text style={styles.subtitle}>Total Students: {students.length}</Text>
        </View>

        <View style={styles.table}>
          <View style={styles.tableHeader}>
            <Text style={styles.colNumber}>#</Text>
            <Text style={styles.colName}>Name</Text>
            <Text style={styles.colStudentNumber}>Student Number</Text>
          </View>

          {students.map((student, i) => (
            <View key={i} style={styles.tableRow}>
              <Text style={styles.colNumber}>{i + 1}</Text>
              <Text style={styles.colName}>{student.name}</Text>
              <Text style={styles.colStudentNumber}>
                {student.studentNumber}
              </Text>
            </View>
          ))}
        </View>

        <View style={styles.footer}>
          <Text style={styles.footerText}>
            Generated by TeachFlow — {new Date().toLocaleDateString()}
          </Text>
        </View>
      </Page>
    </Document>
  )
}
