import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer'

const styles = StyleSheet.create({
  page: { padding: 32, fontSize: 9, fontFamily: 'Helvetica' },
  header: { marginBottom: 16 },
  title: { fontSize: 16, fontWeight: 'bold', marginBottom: 2 },
  subtitle: { fontSize: 10, color: '#666', marginBottom: 1 },
  meta: { fontSize: 9, color: '#888' },
  table: { marginTop: 12 },
  row: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#e5e5e5',
    paddingVertical: 5,
  },
  headerRow: {
    flexDirection: 'row',
    borderBottomWidth: 2,
    borderBottomColor: '#222',
    paddingVertical: 6,
    fontWeight: 'bold',
    backgroundColor: '#f5f5f5',
  },
  colRank: { width: '6%', textAlign: 'center' },
  colName: { width: '32%' },
  colNum: { width: '18%' },
  scoreCell: { width: '11%', textAlign: 'center' },
  colAvg: { width: '11%', textAlign: 'center', fontWeight: 'bold' },
  scoreHigh: { color: '#16a34a' },
  scoreMid: { color: '#ca8a04' },
  scoreLow: { color: '#dc2626' },
  note: { fontSize: 8, color: '#666', marginTop: 10 },
  footer: {
    marginTop: 16,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#e5e5e5',
  },
  footerText: { fontSize: 8, color: '#888' },
})

interface GradebookStudent {
  name: string
  studentNumber: string
  average: number | null
  scores: { title: string; score: number | null; maxScore: number }[]
}

interface Props {
  className: string
  level: string | null
  assessments: { title: string; maxScore: number }[]
  students: GradebookStudent[]
}

export function GradebookReportPDF({
  className,
  level,
  assessments,
  students,
}: Props) {
  return (
    <Document>
      <Page size="A4" orientation="landscape" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>Gradebook Report</Text>
          <Text style={styles.subtitle}>
            {className} {level ? `— ${level}` : ''} • {assessments.length}{' '}
            assessments
          </Text>
          <Text style={styles.meta}>
            Generated by TeachFlow — {new Date().toLocaleDateString('id-ID')}
          </Text>
        </View>

        <View style={styles.table}>
          <View style={styles.headerRow}>
            <Text style={styles.colRank}>#</Text>
            <Text style={styles.colName}>Name</Text>
            <Text style={styles.colNum}>Student No.</Text>
            {assessments.map((a, i) => (
              <Text key={i} style={styles.scoreCell}>
                {a.title.slice(0, 12)}
              </Text>
            ))}
            <Text style={styles.colAvg}>Avg</Text>
          </View>

          {students.map((s, i) => (
            <View key={i} style={styles.row}>
              <Text style={styles.colRank}>{i + 1}</Text>
              <Text style={styles.colName}>{s.name}</Text>
              <Text style={styles.colNum}>{s.studentNumber}</Text>
              {s.scores.map((sc, j) => {
                const pct =
                  sc.score !== null ? (sc.score / sc.maxScore) * 100 : null
                const cs =
                  pct === null
                    ? styles.scoreCell
                    : pct >= 75
                      ? [styles.scoreCell, styles.scoreHigh]
                      : pct >= 50
                        ? [styles.scoreCell, styles.scoreMid]
                        : [styles.scoreCell, styles.scoreLow]
                return (
                  <Text key={j} style={cs}>
                    {sc.score === null ? '–' : `${sc.score}`}
                  </Text>
                )
              })}
              {(() => {
                const a = s.average
                const avgStyle =
                  a === null
                    ? styles.colAvg
                    : a >= 75
                      ? [styles.colAvg, styles.scoreHigh]
                      : a >= 50
                        ? [styles.colAvg, styles.scoreMid]
                        : [styles.colAvg, styles.scoreLow]
                return (
                  <Text style={avgStyle}>
                    {a === null ? '–' : a.toFixed(1)}
                  </Text>
                )
              })()}
            </View>
          ))}
        </View>

        <Text style={styles.note}>
          Average: simple mean (or weighted if assessment weights sum to 100%).
          Scores shown as raw values against each assessment&apos;s max.
        </Text>

        <View style={styles.footer}>
          <Text style={styles.footerText}>
            TeachFlow — Asisten Administrasi untuk Guru
          </Text>
        </View>
      </Page>
    </Document>
  )
}

export interface GradebookReportData {
  className: string
  level: string | null
  assessments: { title: string; maxScore: number }[]
  students: GradebookStudent[]
}
